using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace nilnul.web.http.response
{
	/*
	 Status Line

The first line is called the status line, followed by optional response header(s).

The status line has the following syntax:
HTTP-version status-code reason-phrase
HTTP-version: The HTTP version used in this session. Either HTTP/1.0 and HTTP/1.1.
status-code: a 3-digit number generated by the server to reflect the outcome of the request.
reason-phrase: gives a short explanation to the status code.
 Common status code and reason phrase are "200 OK", "404 Not Found", "403 Forbidden", "500 Internal Server Error".

Examples of status line are:
HTTP/1.1 200 OK
HTTP/1.0 404 Not Found
HTTP/1.1 403 Forbidden

		 */
	public class Status
	{
		public const int Unauthorized = 401;

		/*
		 100: "Continue", 
117 			101: "Switching Protocols", 
118 			102: "Processing", 
119 			200: "OK", 
120 			201: "Created", 
121 			202: "Accepted", 
122 			203: "Non-Authoritative Information", 
123 			204: "No Content", 
124 			205: "Reset Content", 
125 			206: "Partial Content", 
126 			207: "Multi-Status", 
127 			208: "Already Reported", 
128 			226: "IM Used", 
129 			300: "Multiple Choices", 
130 			301: "Moved Permanently", 
131 			302: "Found", 
132 			303: "See Other", 
133 			304: "Not Modified", 
134 			305: "Use Proxy", 
135 			306: "Reserved", 
136 			307: "Temporary Redirect", 
137 			308: "Permanent Redirect", 
138 			400: "Bad Request", 
139 			401: "Unauthorized", 
140 			402: "Payment Required", 
141 			403: "Forbidden", 
142 			404: "Not Found", 
143 			405: "Method Not Allowed", 
144 			406: "Not Acceptable", 
145 			407: "Proxy Authentication Required", 
146 			408: "Request Timeout", 
147 			409: "Conflict", 
148 			410: "Gone", 
149 			411: "Length Required", 
150 			412: "Precondition Failed", 
151 			413: "Request Entity Too Large", 
152 			414: "Request-URI Too Long", 
153 			415: "Unsupported Media Type", 
154 			416: "Requested Range Not Satisfiable", 
155 			417: "Expectation Failed", 
156 			422: "Unprocessable Entity", 
157 			423: "Locked", 
158 			424: "Failed Dependency", 
159 			425: "Unassigned", 
160 			426: "Upgrade Required", 
161 			427: "Unassigned", 
162 			428: "Precondition Required", 
163 			429: "Too Many Requests", 
164 			430: "Unassigned", 
165 			431: "Request Header Fields Too Large", 
166 			500: "Internal Server Error", 
167 			501: "Not Implemented", 
168 			502: "Bad Gateway", 
169 			503: "Service Unavailable", 
170 			504: "Gateway Timeout", 
171 			505: "HTTP Version Not Supported", 
172 			506: "Variant Also Negotiates (Experimental)", 
173 			507: "Insufficient Storage", 
174 			508: "Loop Detected", 
175 			509: "Unassigned", 
176 			510: "Not Extended", 
177 			511: "Network Authentication Required" 

		 */
	}
}
